=== oasp/oasp4j/oasp4j-security/src/main/resources/schema/roles.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://oasp.io/security" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  targetNamespace="http://oasp.io/security" elementFormDefault="qualified">

  <xs:element name="security">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:roles"/>
      </xs:sequence>
    </xs:complexType>

    <xs:key name="roleId">
      <xs:selector xpath="./roles/role"/>
      <xs:field xpath="@name"/>
    </xs:key>
    <xs:keyref name="roleIdRef" refer="tns:roleId">
      <xs:selector xpath="./roles/role/include"/>
      <xs:field xpath="@ref"/>
    </xs:keyref>

  </xs:element>

  <xs:element name="roles">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="tns:role"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="role">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:include" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:permission" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="include">
    <xs:complexType>
      <xs:attribute name="ref" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="permission">
    <xs:complexType>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== oasp/oasp4j/oasp4j-security/src/test/resources/config/accessControlSchema_cyclic.xml
<?xml version="1.0" encoding="UTF-8"?>

<security xmlns="http://oasp.org/security" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://oasp.org/security ../schema/roles.xsd">

  <roles>
    <role name="Waiter">
      <permission name="GET_TABLE"/>
    </role>
    <role name="Barkeeper">
      <include ref="Chief"/>
    </role>
    <role name="Cook">
      <include ref="Barkeeper"/>
    </role>
    <role name="Chief">
      <include ref="Waiter"/>
      <include ref="Barkeeper"/>
      <include ref="Cook"/>
      <permission name="ADD_TABLE"/>
      <permission name="REMOVE_TABLE"/>
    </role>
  </roles>

</security>
